'use strict';
const Music={tracks:[],index:0,active:false,status:'idle',local:[],audio:new Audio(),loaded:false,started:false,requestId:0,duckTimer:null,
 prefs:{volume:.25,muted:false,enabled:true,mode:'list',track:'',duck:true},
 save(){try{localStorage.setItem('jjk_music_native',JSON.stringify(this.prefs));}catch{}},
 read(){try{const p=JSON.parse(localStorage.getItem('jjk_music_native')||'{}');if(Number.isFinite(p.volume))this.prefs.volume=Math.max(0,Math.min(1,p.volume));for(const key of ['muted','enabled','duck'])if(typeof p[key]==='boolean')this.prefs[key]=p[key];if(['list','one','shuffle'].includes(p.mode))this.prefs.mode=p.mode;if(typeof p.track==='string')this.prefs.track=p.track;}catch{}},
 async init(){this.read();
  const button=document.createElement('button');button.id='openMusic';button.className='text-btn';button.textContent='音乐';button.setAttribute('aria-expanded','false');button.setAttribute('aria-controls','musicPanel');document.querySelector('.header-tools').insertBefore(button,$('openMenu'));button.onclick=()=>this.toggle();
  const panel=document.createElement('aside');panel.id='musicPanel';panel.hidden=true;panel.setAttribute('aria-label','游戏背景音乐');panel.innerHTML='<div class="music-heading"><div><small>JUJUTSU RADIO</small><h2>旅途音乐</h2></div><button id="closeMusic" class="text-btn" aria-label="收起音乐面板">收起 ×</button></div><p id="musicNow">正在载入歌单…</p><div class="music-controls"><button id="musicPrev" aria-label="上一曲">上一曲</button><button id="musicPlay">播放</button><button id="musicNext" aria-label="下一曲">下一曲</button><button id="musicStop">关闭音乐</button></div><div id="musicPlayer" class="native-music"><label class="music-seek-label"><span class="sr-only">播放进度</span><input id="musicSeek" type="range" min="0" max="100" value="0" step=".1" aria-label="播放进度" disabled></label><div class="music-time"><span id="musicElapsed">0:00</span><span id="musicDuration">0:00</span></div><div class="music-volume-row"><button id="musicMute" class="gctl-btn" aria-label="音乐静音" aria-pressed="false">静音</button><label>音量 <input id="musicVolume" type="range" min="0" max="100" step="1" aria-label="音乐音量"><output id="musicVolumeValue"></output></label></div><details class="music-settings"><summary>播放设置</summary><div class="music-mode-row"><label>循环 <select id="musicMode"><option value="list">列表循环</option><option value="one">单曲循环</option><option value="shuffle">随机播放</option></select></label><label class="music-duck-label"><input id="musicDuck" type="checkbox">角色说话时降低音乐</label></div></details></div><p class="music-hint" id="musicHint" role="status">首次开始旅程后播放，也可手动选曲。</p><div class="music-filter"><label>季度<select id="musicGroup"><option value="">全部 OP / ED</option></select></label><label>搜索<input id="musicSearch" type="search" placeholder="搜索歌曲或歌手" autocomplete="off"></label></div><p class="music-hint" id="musicCount"></p><div id="musicList" role="list" aria-label="曲目列表"></div><details class="music-import"><summary>添加本地音乐</summary><label>选择音频文件<input id="musicFiles" type="file" accept="audio/*" multiple></label><p class="music-hint">文件仅在本机播放，不上传；刷新后需重新选择。</p></details>';
  document.body.append(panel);$('closeMusic').onclick=()=>{this.toggle(false);button.focus();};panel.onkeydown=e=>{if(e.key==='Escape'){this.toggle(false);button.focus();}};
  $('musicPrev').onclick=()=>this.step(-1);$('musicNext').onclick=()=>this.step(1);$('musicPlay').onclick=()=>['playing','loading'].includes(this.status)?this.pause():this.resume();$('musicStop').onclick=()=>this.stop();
  $('musicGroup').onchange=()=>this.render();$('musicSearch').oninput=()=>this.render();$('musicFiles').onchange=e=>{this.importFiles([...e.target.files]);e.target.value='';};
  $('musicMute').onclick=()=>{this.prefs.muted=!this.prefs.muted;this.audio.muted=this.prefs.muted;this.save();this.sync();};
  $('musicVolume').value=Math.round(this.prefs.volume*100);$('musicVolume').oninput=e=>{this.prefs.volume=Number(e.target.value)/100;this.save();this.applyVolume(true);this.sync();};
  $('musicMode').value=this.prefs.mode;$('musicMode').onchange=e=>{this.prefs.mode=e.target.value;this.save();};$('musicDuck').checked=this.prefs.duck;$('musicDuck').onchange=e=>{this.prefs.duck=e.target.checked;this.save();this.applyVolume(true);};
  this.audio.preload='none';this.audio.muted=this.prefs.muted;this.audio.volume=this.prefs.volume;
  this.audio.onplaying=()=>{this.status='playing';this.active=true;this.message('播放中 · 收起面板也能继续听');clearInterval(this.duckTimer);this.duckTimer=setInterval(()=>this.applyVolume(),120);this.sync();this.render();};
  this.audio.onpause=()=>{this.active=false;clearInterval(this.duckTimer);if(this.status==='playing')this.status='paused';this.sync();};
  this.audio.onloadedmetadata=()=>this.progress();this.audio.ontimeupdate=()=>this.progress();
  this.audio.onended=()=>{this.active=false;clearInterval(this.duckTimer);if(!this.prefs.enabled)return;if(this.prefs.mode==='one'){this.audio.currentTime=0;this.resume();}else this.advanceQueue();};
  this.audio.onerror=()=>{if(this.audio.getAttribute('src')){this.status='error';this.active=false;clearInterval(this.duckTimer);this.message('这首暂时无法播放，可重试或切换下一首。');this.sync();}};
  $('musicSeek').oninput=e=>{$('musicElapsed').textContent=this.time(Number(e.target.value));};$('musicSeek').onchange=e=>this.seek(Number(e.target.value));
  document.addEventListener('click',e=>{if(!this.started&&this.prefs.enabled&&e.target.closest?.('#btnStart,#btnContinue,#btnSpin,#btnActionWheel')){if(this.loaded)this.resume();else this.pendingAuto=true;}});
  const quiet=document.createElement('button');quiet.className='gctl-btn';quiet.id='allSoundOff';quiet.textContent='关闭全部声音';quiet.onclick=()=>{this.stop();SFX.setMuted(true);SFX.setVoice(false);$('btnSound').textContent='音效关';$('btnVoice').textContent='语音关';};$('motionToggle').parentElement.append(quiet);
  new MutationObserver(()=>{const ctl=document.querySelector('.battle-ctl');if(ctl&&!ctl.querySelector('[data-battle-music]')){const b=document.createElement('button');b.className='gctl-btn';b.dataset.battleMusic='';b.textContent='音乐';b.onclick=()=>this.toggle();ctl.append(b);}}).observe($('modalBox'),{childList:true,subtree:true});
  try{const data=await fetch('music-native.json').then(r=>{if(!r.ok)throw Error();return r.json()});if(!Array.isArray(data))throw Error('Invalid music catalogue');this.tracks=data.filter(t=>t.kind==='native'&&/^assets\/music\/v\d+\/[A-Za-z0-9_-]+\.m4a$/.test(t.file));this.groups();let saved=this.prefs.track;try{saved=saved||localStorage.getItem('jjk_music_track');}catch{}const found=this.tracks.findIndex(t=>t.id===saved);if(found>=0)this.index=found;this.loaded=true;this.render();this.sync();if(this.pendingAuto&&this.prefs.enabled){this.pendingAuto=false;this.resume();}}catch{this.loaded=true;this.message('歌单未能加载，可刷新重试或选择本地音乐。');this.sync();}
 },
 message(text){$('musicHint').textContent=text;},
 time(seconds){if(!Number.isFinite(seconds)||seconds<0)return '0:00';seconds=Math.floor(seconds);return Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0');},
 progress(){const duration=this.audio.duration,valid=Number.isFinite(duration)&&duration>0;$('musicSeek').disabled=!valid;$('musicSeek').max=valid?duration:100;$('musicSeek').value=valid?this.audio.currentTime:0;$('musicElapsed').textContent=this.time(this.audio.currentTime);$('musicDuration').textContent=this.time(valid?duration:this.tracks[this.index]?.duration);},
 async seek(seconds){
  const a=this.audio,t=this.tracks[this.index];if(!t||!Number.isFinite(a.duration)||!Number.isFinite(seconds))return;
  const target=Math.max(0,Math.min(a.duration,seconds));
  for(let i=0;i<a.seekable.length;i++)if(target>=a.seekable.start(i)&&target<=a.seekable.end(i)){a.currentTime=target;this.progress();return;}
  if(t.kind==='local'){a.currentTime=target;return;}
  // Some simple static servers cannot serve byte ranges. Buffer only the selected
  // song when seeking, so normal playback still streams and starts immediately.
  const request=++this.requestId,wasPaused=a.paused;this.status='loading';a.pause();this.message('正在准备播放进度…');this.sync();
  try{
   this.seekAbort?.abort();const controller=new AbortController();this.seekAbort=controller;
   const response=await fetch(t.file,{signal:controller.signal});if(!response.ok)throw Error('Audio fetch failed');
   const blob=await response.blob();if(request!==this.requestId)return;
   this.clearSeekBuffer();this.seekURL=URL.createObjectURL(blob);
   await new Promise((resolve,reject)=>{
    let timer;const cleanup=()=>{clearTimeout(timer);a.removeEventListener('loadedmetadata',ready);a.removeEventListener('error',failed);this.cancelSeekLoad=null;};
    const ready=()=>{cleanup();resolve();},failed=()=>{cleanup();reject(Error('Unable to prepare audio'));};
    this.cancelSeekLoad=failed;a.addEventListener('loadedmetadata',ready);a.addEventListener('error',failed);timer=setTimeout(failed,10000);a.src=this.seekURL;a.load();
   });
   if(request!==this.requestId)return;a.currentTime=target;
   if(wasPaused){this.status='paused';this.message('已暂停');}else await this.resume();
   this.progress();this.sync();
  }catch(e){if(request!==this.requestId)return;this.status='paused';this.message('进度暂时无法调整，可继续播放或切换歌曲。');this.sync();}
 },
 clearSeekBuffer(){if(this.seekURL){URL.revokeObjectURL(this.seekURL);this.seekURL=null;}},
 applyVolume(immediate=false){const speaking=this.prefs.duck&&(window.AnimeVoice?.remainingMs()>0||window.AnimeVoice?.fallbackDomain||window.speechSynthesis?.speaking);const target=this.prefs.volume*(speaking ? .25 : 1);this.audio.volume=immediate?target:this.audio.volume+(target-this.audio.volume)*.45;},
 sync(){const t=this.tracks[this.index];$('musicNow').textContent=t?t.title:(this.loaded?'暂无可播放曲目':'正在载入歌单…');$('musicPlay').textContent=this.status==='loading'?'暂停':['playing'].includes(this.status)?'暂停':this.status==='paused'?'继续':'播放';$('openMusic').textContent=this.active?'音乐 · 开':'音乐';$('musicMute').textContent=this.prefs.muted?'取消静音':'静音';$('musicMute').setAttribute('aria-pressed',String(this.prefs.muted));$('musicVolumeValue').textContent=Math.round(this.prefs.volume*100)+'%';for(const id of ['musicPlay','musicNext','musicPrev'])$(id).disabled=!this.tracks.length;},
 toggle(value){const open=value??$('musicPanel').hidden;$('musicPanel').hidden=!open;$('openMusic').setAttribute('aria-expanded',String(open));document.body.classList.toggle('music-open',open);},
 groups(){const s=$('musicGroup');for(const group of new Set(this.tracks.map(t=>t.group))){if([...s.options].some(o=>o.value===group))continue;const o=document.createElement('option');o.value=o.textContent=group;s.append(o);}},
 filtered(){const query=$('musicSearch').value.trim().toLowerCase(),group=$('musicGroup').value;return this.tracks.map((t,i)=>({...t,i})).filter(t=>(!group||t.group===group)&&(!query||(t.title+' '+t.group+' '+(t.artist||'')+' '+(t.theme||'')).toLowerCase().includes(query)));},
 render(){const list=$('musicList'),rows=this.filtered();list.replaceChildren();$('musicCount').textContent=rows.length+' 首 / '+this.tracks.length+' 首';if(!rows.length){list.textContent='没有匹配的曲目';return;}for(const t of rows){const b=document.createElement('button');b.className='music-track';b.setAttribute('aria-pressed',String(t.i===this.index&&this.active));const title=document.createElement('span'),sub=document.createElement('small');title.textContent=t.title;sub.textContent=[t.group,t.theme,t.artist,this.time(t.duration)].filter(Boolean).join(' · ');b.append(title,sub);b.onclick=()=>this.play(t.i);list.append(b);}},
 pause(){this.requestId++;this.seekAbort?.abort();this.cancelSeekLoad?.();this.status='paused';this.audio.pause();this.active=false;clearInterval(this.duckTimer);this.message('已暂停');this.sync();this.render();},
 stop(){this.pendingAuto=false;this.prefs.enabled=false;this.save();this.pause();this.status='off';this.message('音乐已关闭');this.sync();},
 async resume(){if(!this.tracks.length)return;const t=this.tracks[this.index];if(this.sourceId!==t.id||!this.audio.getAttribute('src'))return this.play(this.index);this.started=true;this.prefs.enabled=true;this.save();const request=++this.requestId;this.status='loading';this.sync();try{await this.audio.play();}catch(e){if(request!==this.requestId)return;this.status=e.name==='NotAllowedError'?'paused':'error';this.active=false;this.message(e.name==='NotAllowedError'?'点击播放即可开启音乐。':'这首暂时无法播放，可重试或切换下一首。');this.sync();}},
 play(i){if(!Number.isInteger(i)||!this.tracks[i])return;this.requestId++;this.seekAbort?.abort();this.cancelSeekLoad?.();this.clearSeekBuffer();this.status='loading';this.audio.pause();this.active=false;clearInterval(this.duckTimer);this.index=i;const t=this.tracks[i];this.sourceId=t.id;this.prefs.track=t.kind==='local'?'':t.id;this.prefs.enabled=true;this.started=true;this.audio.src=t.kind==='local'?t.url:t.file;this.audio.muted=this.prefs.muted;this.applyVolume(true);const group=$('musicGroup').value;this.queue=this.tracks.filter(r=>!group||r.group===group).map(r=>r.id);if(!this.queue.includes(t.id))this.queue=this.tracks.filter(r=>r.group===t.group).map(r=>r.id);this.save();this.progress();this.render();this.message('正在加载音频…');return this.resume();},
 step(delta){const rows=this.filtered();if(!rows.length)return;const at=rows.findIndex(t=>t.i===this.index);const next=at<0?(delta>0?0:rows.length-1):(at+delta+rows.length)%rows.length;return this.play(rows[next].i);},
 advanceQueue(){const ids=this.queue?.length?this.queue:this.tracks.map(t=>t.id),current=this.tracks[this.index]?.id;let next;if(this.prefs.mode==='shuffle'){const other=ids.filter(id=>id!==current);next=other.length?other[Math.floor(Math.random()*other.length)]:current;}else next=ids[(ids.indexOf(current)+1)%ids.length];const i=this.tracks.findIndex(t=>t.id===next),queue=[...ids];if(i>=0){this.play(i);this.queue=queue;}},
 importFiles(files){for(const f of files){if(!f.type.startsWith('audio/')&&!/\.(mp3|wav|ogg|m4a|flac)$/i.test(f.name))continue;const url=URL.createObjectURL(f);this.local.push(url);this.tracks.push({id:'local-'+this.local.length,kind:'local',title:f.name,group:'本地音乐',url});}this.groups();$('musicGroup').value='本地音乐';this.render();this.sync();}
};window.Music=Music;Music.init();
window.addEventListener('pagehide',()=>{Music.audio.pause();clearInterval(Music.duckTimer);});
