(() => {
 'use strict';const $=id=>document.getElementById(id),frame=$('stage'),asset=f=>new URL('assets/'+f,location.href).href;
 let catalog,selected='summon-dog',ready=false,loaded=false,serial=0,actionId=0,frozen='';
 const notes={dog:'四足扑咬，前爪与头部先行。',frog:'低伏蓄势、伸舌牵制，保持腹部符号。',rabbit:'双兔跃击，以后腿蹬地起身。',deer:'低头角击；四眼与枝角保留。',ox:'后蹄蹬地，角先行的重冲锋。',elephant:'抬鼻蓄势、前伸象鼻。',nue:'面具与羽翼保持原作识别，俯冲爪击。',serpent:'白色蛇身盘绕，伸颈咬击。',puppet:'机械肩肘起手与前臂刃斩击。',crow:'羽翼收展、俯冲啄击。',fused:'原版任意式神融合规则沿用；此图为依据漫画顎吐头部转绘的游戏融合形象。',mecha:'动画绝对形态造型转绘；四个独立姿势，用于原版扩展领域。'};
 function send(payload){if(ready)frame.contentWindow.postMessage({channel:'jjk-battle',payload},location.origin);}
 function sync(){if(!catalog)return;const a=catalog.actors[selected],enemy=catalog.actors.kechizu;send({type:'state',rosterKey:'summon-review-'+serial,presentation:'player-sample',artReview:true,active:!document.hidden,quality:'fine',target:1,surfaceAtlas:asset(catalog.surfaceAtlas),environment:{key:'bridge',painted:true,url:asset('scenes/v1/bridge-night.png')},domains:[],roster:[{index:0,name:a.label,side:'ally',alive:true,height:a.height,url:asset(a.file),maskURL:asset(a.maskFile),battleSprite:{...a,summonUnit:true},reviewPose:frozen},{index:1,name:'血涂',side:'enemy',alive:true,height:enemy.height,url:asset(enemy.file),battleSprite:enemy}]});}
 function draw(){const a=catalog.actors[selected];$('name').textContent=a.label;$('note').textContent=notes[selected.replace('summon-','')];$('poses').replaceChildren();for(const [key,label] of [['idle','待机'],['idle2','呼吸'],['windup','蓄势'],['attack','命中'],['hit','受击'],['defeat','退场']]){const f=a.poses[key]??0,b=document.createElement('button');b.className='pose';b.setAttribute('aria-pressed',String(frozen===key));const img=document.createElement('img');img.src=asset(a.poseFiles[f]);img.alt=a.label+' · '+label;const s=document.createElement('span');s.textContent=label;b.append(img,s);b.onclick=()=>{frozen=key;sync();draw();};$('poses').append(b);}for(const b of $('gallery').children)b.setAttribute('aria-pressed',String(b.dataset.key===selected));}
 function choose(key){selected=key;serial++;loaded=false;frozen='';$('attack').disabled=true;draw();sync();}
 $('attack').onclick=()=>{if(!loaded)return;frozen='';sync();draw();const a=catalog.actors[selected];send({type:'event',eventType:'choreography',presentationOnly:true,id:++actionId,fromIndex:0,toIndex:1,actionKind:selected==='summon-mecha'?'cannon':'melee',variant:a.summonAction||''});};
 $('idle').onclick=()=>{frozen='';sync();draw();};
 window.addEventListener('message',e=>{if(e.source!==frame.contentWindow||e.origin!==location.origin||e.data?.channel!=='jjk-battle')return;const d=e.data;if(d.type==='ready'){ready=true;sync();}if(d.type==='state'&&d.rosterKey==='summon-review-'+serial){loaded=d.loaded===2&&d.backgroundReady;$('attack').disabled=!loaded;$('status').textContent=loaded?'舞台已就绪 · 左侧召唤物 / 右侧敌方':'正在载入…';}if(d.type==='error'||d.type==='asset-error')$('status').textContent='舞台载入未完成，下方可先查看动作。';});
 document.addEventListener('visibilitychange',()=>send({type:'pause',value:document.hidden}));
 fetch('battle-sprites.json').then(r=>{if(!r.ok)throw Error('图集未载入');return r.json();}).then(c=>{catalog=c;for(const [key,a] of Object.entries(c.actors).filter(([k])=>k.startsWith('summon-'))){const b=document.createElement('button');b.dataset.key=key;const img=document.createElement('img');img.src=asset(a.posterFile);img.alt=a.label;const name=document.createElement('strong');name.textContent=a.label;b.append(img,name);b.onclick=()=>choose(key);$('gallery').append(b);}choose(selected);}).catch(e=>$('status').textContent=e.message);
})();
